package com.mongol.encode;

public class MCodeConstant {
	
	public static final char  UNI0020_SPACE			= '\u0020';
	public static final char  UNI007E_TILDE			= '\u0020';
	
	public static final char  UNI200C_ZWNJ 			= '\u200C';
	public static final char  UNI200D_ZWJ 			= '\u200D';
	public static final char  UNI202F_NOBREAK 		= '\u202F';
	
	// Mongolian Unicode Definition -- simbols
	public static final char  UNI1800_BIRGA 		= '\u1800';
	public static final char  UNI1801_ELLIPSIS 		= '\u1801';
	public static final char  UNI1802_COMMA 		= '\u1802';
	public static final char  UNI1803_FULLSTOP 		= '\u1803';
	public static final char  UNI1804_COLON 		= '\u1804';
	public static final char  UNI1805_FOURDOT 		= '\u1805';
	public static final char  UNI1806 				= '\u1806';
	public static final char  UNI1807				= '\u1807';
	public static final char  UNI1808				= '\u1808';
	public static final char  UNI1809				= '\u1809';
	public static final char  UNI180A_NIRUGU		= '\u180A';
	
	// Mongolian Unicode Definition -- control code
	public static final char  UNI180B_FVS1			= '\u180B';
	public static final char  UNI180C_FVS2			= '\u180C';
	public static final char  UNI180D_FVS3			= '\u180D';
	public static final char  UNI180E_MVS 			= '\u180E';
	
	// Mongolian Unicode Definition -- digit
	public static final char  UNI1810_ZERO 			= '\u1810';
	public static final char  UNI1811_ONE 			= '\u1811';
	public static final char  UNI1812_TWO 			= '\u1812';
	public static final char  UNI1813_THREE 		= '\u1813';
	public static final char  UNI1814_FOUE 			= '\u1814';
	public static final char  UNI1815_FIVE 			= '\u1815';
	public static final char  UNI1816_SIX 			= '\u1816';
	public static final char  UNI1817_SEVEN 		= '\u1817';
	public static final char  UNI1818_EIGHT 		= '\u1818';
	public static final char  UNI1819_NINE 			= '\u1819';
	
	// Mongolian Unicode Definition -- mongolian
	public static final char  UNI1820_A 			= '\u1820';
	public static final char  UNI1821_E 			= '\u1821';
	public static final char  UNI1822_I 			= '\u1822';
	public static final char  UNI1823_O 			= '\u1823';
	public static final char  UNI1824_U 			= '\u1824';
	public static final char  UNI1825_OE 			= '\u1825';
	public static final char  UNI1826_UE 			= '\u1826';
	public static final char  UNI1827_EE 			= '\u1827';
	public static final char  UNI1828_N 			= '\u1828';
	public static final char  UNI1829_NG 			= '\u1829';
	public static final char  UNI182A_B 			= '\u182A';
	public static final char  UNI182B_P 			= '\u182B';
	public static final char  UNI182C_H 			= '\u182C';
	public static final char  UNI182D_G 			= '\u182D';
	public static final char  UNI182E_M 			= '\u182E';
	public static final char  UNI182F_L 			= '\u182F';
	public static final char  UNI1830_S 			= '\u1830';
	public static final char  UNI1831_SH 			= '\u1831';
	public static final char  UNI1832_T 			= '\u1832';
	public static final char  UNI1833_D 			= '\u1833';
	public static final char  UNI1834_CH 			= '\u1834';
	public static final char  UNI1835_J 			= '\u1835';
	public static final char  UNI1836_Y 			= '\u1836';
	public static final char  UNI1837_R 			= '\u1837';
	public static final char  UNI1838_W 			= '\u1838';
	public static final char  UNI1839_F 			= '\u1839';
	public static final char  UNI183A_K 			= '\u183A';
	public static final char  UNI183B_KH 			= '\u183B';
	public static final char  UNI183C_TS 			= '\u183C';
	public static final char  UNI183D_Z 			= '\u183D';
	public static final char  UNI183E_HH 			= '\u183E';
	public static final char  UNI183F_RH 			= '\u183F';
	public static final char  UNI1840_LH 			= '\u1840';
	public static final char  UNI1841_ZH 			= '\u1841';
	public static final char  UNI1842_CHI 			= '\u1842';
	
	public static final char  UNI18AA_AU 			= '\u18AA';

	// Mongolian Glyph Definition -- simbols
	public static final char  UNIE800_BIRGA 				= '\uE800';
	public static final char  UNIE801_ELLIPSIS 				= '\uE801';
	public static final char  UNIE802_COMMA 				= '\uE802';
	public static final char  UNIE803_FULLSTOP 				= '\uE803';
	public static final char  UNIE804_COLON 				= '\uE804';
	public static final char  UNIE805_FOURDOT 				= '\uE805';
	public static final char  UNIE806		 				= '\uE806';
	public static final char  UNIE807		 				= '\uE807';
	public static final char  UNIE808		 				= '\uE808';
	public static final char  UNIE809		 				= '\uE809';
	public static final char  UNIE80A_NIRUGU 				= '\uE80A';
	public static final char  UNIE80B 						= '\uE80B';
	public static final char  UNIE80C 						= '\uE80C';
	public static final char  UNIE80D 						= '\uE80D';
	public static final char  UNIE80E		 				= '\uE80E';
	public static final char  UNIE80F_SMALLTAIL	 			= '\uE80F';	// added 2012/10/29
	
	// Mongolian Glyph Definition -- digit
	public static final char  UNIE810_ZERO 					= '\uE810';
	public static final char  UNIE811_ONE 					= '\uE811';
	public static final char  UNIE812_TWO	 				= '\uE812';
	public static final char  UNIE813_THREE 				= '\uE813';
	public static final char  UNIE814_FOUR 					= '\uE814';
	public static final char  UNIE815_FIVE 					= '\uE815';	
	public static final char  UNIE816_SIX 					= '\uE816';
	public static final char  UNIE817_SEVEN 				= '\uE817';
	public static final char  UNIE818_EIGHT 				= '\uE818';
	public static final char  UNIE819_NINE 					= '\uE819';
	public static final char  UNIE81A		 				= '\uE81A'; // ?!
	public static final char  UNIE81B		 				= '\uE81B'; // !?
	public static final char  UNIE81C		 				= '\uE81C'; // !
	public static final char  UNIE81D		 				= '\uE81D'; // ?
	public static final char  UNIE81E		 				= '\uE81E'; // ;
	public static final char  UNIE81F		 				= '\uE81F'; // ,

	// Mongolian Glyph Definition -- mongolian
	public static final char  UNIE820_A_ISOL		 		= '\uE820';
	public static final char  UNIE821_A_ISOL_VAR1			= '\uE821';
	public static final char  UNIE822_A_INIT		 		= '\uE822';
	public static final char  UNIE823_A_MEDI		 		= '\uE823';
	public static final char  UNIE824_A_MEDI_VAR1		 	= '\uE824';
	public static final char  UNIE825_A_FINA		 		= '\uE825';
	public static final char  UNIE826_A_FINA_VAR1		 	= '\uE826';
	public static final char  UNIE827_A_FINA_VAR2		 	= '\uE827';
	public static final char  UNIE828_E_ISOL		 		= '\uE828';
	public static final char  UNIE829_E_ISOL_VAR1		 	= '\uE829';
	public static final char  UNIE82A_E_INIT		 		= '\uE82A';
	public static final char  UNIE82B_E_INIT_VAR1		 	= '\uE82B';
	public static final char  UNIE82C_E_MEDI		 		= '\uE82C';
	public static final char  UNIE82D_E_FINA		 		= '\uE82D';
	public static final char  UNIE82E_E_FINA_VAR1		 	= '\uE82E';
	public static final char  UNIE82F_E_FINA_VAR2		 	= '\uE82F';
	public static final char  UNIE830_I_ISOL		 		= '\uE830';
	public static final char  UNIE831_I_ISOL_VAR1		 	= '\uE831';
	public static final char  UNIE832_I_INIT		 		= '\uE832';
	public static final char  UNIE833_I_INIT_VAR1		 	= '\uE833';
	public static final char  UNIE834_I_MEDI		 		= '\uE834';
	public static final char  UNIE835_I_MEDI_VAR1		 	= '\uE835';
	public static final char  UNIE836_I_MEDI_VAR2		 	= '\uE836';
	public static final char  UNIE837_I_FINA		 		= '\uE837';
	public static final char  UNIE838_O_ISOL		 		= '\uE838';
	public static final char  UNIE839_O_ISOL_VAR1			= '\uE839';
	public static final char  UNIE83A_O_INIT		 		= '\uE83A';
	public static final char  UNIE83B_O_INIT_VAR1		 	= '\uE83B';
	public static final char  UNIE83C_O_MEDI		 		= '\uE83C';
	public static final char  UNIE83D_O_MEDI_VAR1		 	= '\uE83D';
	public static final char  UNIE83E_O_FINA		 		= '\uE83E';
	public static final char  UNIE83F_O_FINA_VAR1		 	= '\uE83F';
	public static final char  UNIE840_U_ISOL		 		= '\uE840';
	public static final char  UNIE841_U_ISOL_VAR2		 	= '\uE841';
	public static final char  UNIE842_U_INIT			 	= '\uE842';
	public static final char  UNIE843_U_INIT_VAR1		 	= '\uE843';
	public static final char  UNIE844_U_MEDI			 	= '\uE844';
	public static final char  UNIE845_U_MEDI_VAR1		 	= '\uE845';
	public static final char  UNIE846_U_FINA			 	= '\uE846';
	public static final char  UNIE847_U_FINA_VAR1		 	= '\uE847';
	public static final char  UNIE848_OE_ISOL		 		= '\uE848';
	public static final char  UNIE849_OE_ISOL_VAR1		 	= '\uE849';
	public static final char  UNIE84A_OE_INIT			 	= '\uE84A';
	public static final char  UNIE84B_OE_MEDI			 	= '\uE84B';
	public static final char  UNIE84C_OE_MEDI_VAR1			= '\uE84C';
	public static final char  UNIE84D_OE_MEDI_VAR2			= '\uE84D';
	public static final char  UNIE84E_OE_FINA			 	= '\uE84E';
	public static final char  UNIE84F_OE_FINA_VAR1			= '\uE84F';
	public static final char  UNIE850_UE_ISOL			 	= '\uE850';
	public static final char  UNIE851_UE_ISOL_VAR3			= '\uE851';
	public static final char  UNIE852_UE_INIT			 	= '\uE852';
	public static final char  UNIE853_UE_MEDI			 	= '\uE853';
	public static final char  UNIE854_UE_MEDI_VAR1			= '\uE854';
	public static final char  UNIE855_UE_MEDI_VAR2			= '\uE855';
	public static final char  UNIE856_UE_FINA			 	= '\uE856';
	public static final char  UNIE857_UE_FINA_VAR1			= '\uE857';
	public static final char  UNIE858_EE_ISOL			 	= '\uE858';
	public static final char  UNIE859_EE_ISOL_VAR1			= '\uE859';
	public static final char  UNIE85A_EE_INIT			 	= '\uE85A';
	public static final char  UNIE85B_EE_INIT_VAR1			= '\uE85B';
	public static final char  UNIE85C_EE_MEDI			 	= '\uE85C';
	public static final char  UNIE85D_EE_FINA			 	= '\uE85D';
	public static final char  UNIE85E_UE_INIT_VAR1			= '\uE85E';	// added 2012/10/29
	public static final char  UNIE85F_UE_ISOL_VAR1			= '\uE85F';
	// N
	public static final char  UNIE860_N_ISOL			 	= '\uE860';
	public static final char  UNIE861_N_ISOL_VAR1			= '\uE861';
	public static final char  UNIE862_N_INIT			 	= '\uE862';
	public static final char  UNIE863_N_INIT_VAR1			= '\uE863';
	public static final char  UNIE864_N_MEDI			 	= '\uE864';
	public static final char  UNIE865_N_MEDI_VAR1			= '\uE865';
	public static final char  UNIE866_N_FINA				= '\uE866';
	public static final char  UNIE867_N_FINA_VAR1			= '\uE867';
	public static final char  UNIE868_NG_ISOL				= '\uE868';
	public static final char  UNIE869_NG_INIT				= '\uE869';
	public static final char  UNIE86A_NG_MEDI				= '\uE86A';
	public static final char  UNIE86B_NG_FINA				= '\uE86B';
	public static final char  UNIE86C_NGH_MEDI				= '\uE86C';
	public static final char  UNIE86D_NGG_MEDI				= '\uE86D';
	public static final char  UNIE86E_NGM_MEDI				= '\uE86E';
	public static final char  UNIE86F_NGL_MEDI				= '\uE86F';
	// B
	public static final char  UNIE870_B_ISOL				= '\uE870';
	public static final char  UNIE871_B_INIT				= '\uE871';
	public static final char  UNIE872_B_MEDI				= '\uE872';
	public static final char  UNIE873_B_FINA				= '\uE873';
	public static final char  UNIE874_BA_ISOL				= '\uE874';
	public static final char  UNIE875_BA_INIT				= '\uE875';
	public static final char  UNIE876_BA_MEDI				= '\uE876';
	public static final char  UNIE877_BA_FINA				= '\uE877';
	public static final char  UNIE878_BE_ISOL				= '\uE878';
	public static final char  UNIE879_BE_INIT				= '\uE879';
	public static final char  UNIE87A_BE_MEDI				= '\uE87A';
	public static final char  UNIE87B_BE_FINA				= '\uE87B';
	public static final char  UNIE87C_BI_ISOL				= '\uE87C';
	public static final char  UNIE87D_BI_INIT				= '\uE87D';
	public static final char  UNIE87E_BI_MEDI				= '\uE87E';
	public static final char  UNIE87F_BI_FINA				= '\uE87F';
	public static final char  UNIE880_BO_ISOL				= '\uE880';
	public static final char  UNIE881_BO_INIT				= '\uE881';
	public static final char  UNIE882_BO_MEDI				= '\uE882';
	public static final char  UNIE883_BO_FINA				= '\uE883';
	public static final char  UNIE884_BU_ISOL				= '\uE884';
	public static final char  UNIE885_BU_INIT				= '\uE885';
	public static final char  UNIE886_BU_MEDI				= '\uE886';
	public static final char  UNIE887_BU_FINA				= '\uE887';
	public static final char  UNIE888_BOE_ISOL				= '\uE888';
	public static final char  UNIE889_BOE_INIT				= '\uE889';
	public static final char  UNIE88A_BOE_MEDI				= '\uE88A';
	public static final char  UNIE88B_BOE_FINA				= '\uE88B';
	public static final char  UNIE88C_BOE_FINA_VAR1			= '\uE88C';
	public static final char  UNIE88D_BUE_ISOL				= '\uE88D';
	public static final char  UNIE88E_BUE_INIT				= '\uE88E';
	public static final char  UNIE88F_BUE_MEDI				= '\uE88F';
	public static final char  UNIE890_BUE_FINA				= '\uE890';
	public static final char  UNIE891_BUE_FINA_VAR1			= '\uE891';
	public static final char  UNIE892_BEE_ISOL				= '\uE892';
	public static final char  UNIE893_BEE_INIT				= '\uE893';
	public static final char  UNIE894_BEE_MEDI				= '\uE894';
	public static final char  UNIE895_BEE_FINA				= '\uE895';
	public static final char  UNIE896_BM_MEDI				= '\uE896';
	public static final char  UNIE897_BL_MEDI				= '\uE897';
	// P
	public static final char  UNIE898_P_ISOL				= '\uE898';
	public static final char  UNIE899_P_INIT				= '\uE899';
	public static final char  UNIE89A_P_MEDI				= '\uE89A';
	public static final char  UNIE89B_P_FINA				= '\uE89B';
	public static final char  UNIE89C_PA_ISOL				= '\uE89C';
	public static final char  UNIE89D_PA_INIT				= '\uE89D';
	public static final char  UNIE89E_PA_MEDI				= '\uE89E';
	public static final char  UNIE89F_PA_FINA				= '\uE89F';
	public static final char  UNIE8A0_PE_ISOL				= '\uE8A0';
	public static final char  UNIE8A1_PE_INIT				= '\uE8A1';
	public static final char  UNIE8A2_PE_MEDI				= '\uE8A2';
	public static final char  UNIE8A3_PE_FINA				= '\uE8A3';
	public static final char  UNIE8A4_PI_ISOL				= '\uE8A4';
	public static final char  UNIE8A5_PI_INIT				= '\uE8A5';
	public static final char  UNIE8A6_PI_MEDI				= '\uE8A6';
	public static final char  UNIE8A7_PI_FINA				= '\uE8A7';
	public static final char  UNIE8A8_PO_ISOL				= '\uE8A8';
	public static final char  UNIE8A9_PO_INIT				= '\uE8A9';
	public static final char  UNIE8AA_PO_MEDI				= '\uE8AA';
	public static final char  UNIE8AB_PO_FINA				= '\uE8AB';
	public static final char  UNIE8AC_PU_ISOL				= '\uE8AC';
	public static final char  UNIE8AD_PU_INIT				= '\uE8AD';
	public static final char  UNIE8AE_PU_MEDI				= '\uE8AE';
	public static final char  UNIE8AF_PU_FINA				= '\uE8AF';
	public static final char  UNIE8B0_POE_ISOL				= '\uE8B0';
	public static final char  UNIE8B1_POE_INIT				= '\uE8B1';
	public static final char  UNIE8B2_POE_MEDI				= '\uE8B2';
	public static final char  UNIE8B3_POE_FINA				= '\uE8B3';
	public static final char  UNIE8B4_POE_FINA_VAR1			= '\uE8B4';
	public static final char  UNIE8B5_PUE_ISOL				= '\uE8B5';
	public static final char  UNIE8B6_PUE_INIT				= '\uE8B6';
	public static final char  UNIE8B7_PUE_MEDI				= '\uE8B7';
	public static final char  UNIE8B8_PUE_FINA				= '\uE8B8';
	public static final char  UNIE8B9_PUE_FINA_VAR1			= '\uE8B9';
	public static final char  UNIE8BA_PEE_ISOL				= '\uE8BA';
	public static final char  UNIE8BB_PEE_INIT				= '\uE8BB';
	public static final char  UNIE8BC_PEE_MEDI				= '\uE8BC';
	public static final char  UNIE8BD_PEE_FINA				= '\uE8BD';
	public static final char  UNIE8BE_PM_MEDI				= '\uE8BE';
	public static final char  UNIE8BF_PL_MEDI				= '\uE8BF';
	// H
	public static final char  UNIE8C0_H_ISOL				= '\uE8C0';
	public static final char  UNIE8C1_H_ISOL_VAR3			= '\uE8C1';
	public static final char  UNIE8C2_H_INIT				= '\uE8C2';
	public static final char  UNIE8C3_H_INIT_VAR1			= '\uE8C3';
	public static final char  UNIE8C4_H_MEDI				= '\uE8C4';
	public static final char  UNIE8C5_H_MEDI_VAR1			= '\uE8C5';
	public static final char  UNIE8C6_H_MEDI_VAR3			= '\uE8C6';
	public static final char  UNIE8C7_H_FINA				= '\uE8C7';
	public static final char  UNIE8C8_H_FINA_VAR1			= '\uE8C8';
	public static final char  UNIE8C9_H_FINA_VAR2			= '\uE8C9';
	public static final char  UNIE8CA_HE_ISOL				= '\uE8CA';
	public static final char  UNIE8CB_HE_INIT				= '\uE8CB';
	public static final char  UNIE8CC_HE_MEDI				= '\uE8CC';
	public static final char  UNIE8CD_HE_FINA				= '\uE8CD';
	public static final char  UNIE8CE_HI_ISOL				= '\uE8CE';
	public static final char  UNIE8CF_HI_INIT				= '\uE8CF';
	public static final char  UNIE8D0_HI_MEDI				= '\uE8D0';
	public static final char  UNIE8D1_HI_FINA				= '\uE8D1';
	public static final char  UNIE8D2_HOE_ISOL				= '\uE8D2';
	public static final char  UNIE8D3_HOE_INIT				= '\uE8D3';
	public static final char  UNIE8D4_HOE_MEDI				= '\uE8D4';
	public static final char  UNIE8D5_HOE_FINA				= '\uE8D5';
	public static final char  UNIE8D6_HOE_FINA_VAR1			= '\uE8D6';
	public static final char  UNIE8D7_HUE_ISOL				= '\uE8D7';
	public static final char  UNIE8D8_HUE_INIT				= '\uE8D8';
	public static final char  UNIE8D9_HUE_MEDI				= '\uE8D9';
	public static final char  UNIE8DA_HUE_FINA				= '\uE8DA';
	public static final char  UNIE8DB_HUE_FINA_VAR1			= '\uE8DB';
	public static final char  UNIE8DC_HEE_ISOL				= '\uE8DC';
	public static final char  UNIE8DD_HEE_INIT				= '\uE8DD';
	public static final char  UNIE8DE_HEE_MEDI				= '\uE8DE';
	public static final char  UNIE8DF_HEE_FINA				= '\uE8DF';
	// G
	public static final char  UNIE8E0_G_ISOL				= '\uE8E0';
	public static final char  UNIE8E1_G_ISOL_VAR3			= '\uE8E1';
	public static final char  UNIE8E2_G_INIT				= '\uE8E2';
	public static final char  UNIE8E3_G_INIT_VAR1			= '\uE8E3';
	public static final char  UNIE8E4_G_MEDI				= '\uE8E4';
	public static final char  UNIE8E5_G_MEDI_VAR1			= '\uE8E5';
	public static final char  UNIE8E6_G_MEDI_VAR2			= '\uE8E6';
	public static final char  UNIE8E7_G_FINA				= '\uE8E7';
	public static final char  UNIE8E8_G_FINA_VAR1			= '\uE8E8';
	public static final char  UNIE8E9_G_FINA_VAR2			= '\uE8E9';
	public static final char  UNIE8EA_GE_ISOL				= '\uE8EA';
	public static final char  UNIE8EB_GE_INIT				= '\uE8EB';
	public static final char  UNIE8EC_GE_MEDI				= '\uE8EC';
	public static final char  UNIE8ED_GE_FINA				= '\uE8ED';
	public static final char  UNIE8EE_GI_ISOL				= '\uE8EE';
	public static final char  UNIE8EF_GI_INIT				= '\uE8EF';
	public static final char  UNIE8F0_GI_MEDI				= '\uE8F0';
	public static final char  UNIE8F1_GI_FINA				= '\uE8F1';
	public static final char  UNIE8F2_GOE_ISOL				= '\uE8F2';
	public static final char  UNIE8F3_GOE_INIT				= '\uE8F3';
	public static final char  UNIE8F4_GOE_MEDI				= '\uE8F4';
	public static final char  UNIE8F5_GOE_FINA				= '\uE8F5';
	public static final char  UNIE8F6_GOE_FINA_VAR1			= '\uE8F6';
	public static final char  UNIE8F7_GUE_ISOL				= '\uE8F7';
	public static final char  UNIE8F8_GUE_INIT				= '\uE8F8';
	public static final char  UNIE8F9_GUE_MEDI				= '\uE8F9';
	public static final char  UNIE8FA_GUE_FINA				= '\uE8FA';
	public static final char  UNIE8FB_GUE_FINA_VAR1			= '\uE8FB';
	public static final char  UNIE8FC_GEE_ISOL				= '\uE8FC';
	public static final char  UNIE8FD_GEE_INIT				= '\uE8FD';
	public static final char  UNIE8FE_GEE_MEDI				= '\uE8FE';
	public static final char  UNIE8FF_GEE_FINA				= '\uE8FF';
	public static final char  UNIE900_GM_MEDI				= '\uE900';
	public static final char  UNIE901_GL_MEDI				= '\uE901';
	// M
	public static final char  UNIE902_M_ISOL				= '\uE902';
	public static final char  UNIE903_M_INIT				= '\uE903';
	public static final char  UNIE904_M_MEDI				= '\uE904';
	public static final char  UNIE905_M_FINA				= '\uE905';
	// L
	public static final char  UNIE906_L_ISOL				= '\uE906';
	public static final char  UNIE907_L_INIT				= '\uE907';
	public static final char  UNIE908_L_MEDI				= '\uE908';
	public static final char  UNIE909_L_FINA				= '\uE909';
	// S
	public static final char  UNIE90A_S_ISOL				= '\uE90A';
	public static final char  UNIE90B_S_INIT				= '\uE90B';
	public static final char  UNIE90C_S_MEDI				= '\uE90C';
	public static final char  UNIE90D_S_FINA				= '\uE90D';
	// SH
	public static final char  UNIE90E_SH_ISOL				= '\uE90E';
	public static final char  UNIE90F_SH_INIT				= '\uE90F';
	public static final char  UNIE910_SH_MEDI				= '\uE910';
	public static final char  UNIE911_SH_FINA				= '\uE911';
	// T
	public static final char  UNIE912_T_ISOL				= '\uE912';
	public static final char  UNIE913_T_ISOL_VAR1			= '\uE913';
	public static final char  UNIE914_T_INIT				= '\uE914';
	public static final char  UNIE915_T_MEDI				= '\uE915';
	public static final char  UNIE916_T_MEDI_VAR1			= '\uE916';
	public static final char  UNIE917_T_MEDI_VAR2			= '\uE917';
	public static final char  UNIE918_T_FINA				= '\uE918';
	// D
	public static final char  UNIE919_D_ISOL				= '\uE919';
	public static final char  UNIE91A_D_INIT				= '\uE91A';
	public static final char  UNIE91B_D_INIT_VAR1			= '\uE91B';
	public static final char  UNIE91C_D_MEDI				= '\uE91C';
	public static final char  UNIE91D_D_MEDI_VAR1			= '\uE91D';
	public static final char  UNIE91E_D_FINA				= '\uE91E';
	public static final char  UNIE91F_D_FINA_VAR1			= '\uE91F';
	// CH
	public static final char  UNIE920_CH_ISOL				= '\uE920';
	public static final char  UNIE921_CH_INIT				= '\uE921';
	public static final char  UNIE922_CH_MEDI				= '\uE922';
	public static final char  UNIE923_CH_FINA				= '\uE923';
	// J
	public static final char  UNIE924_J_ISOL				= '\uE924';
	public static final char  UNIE925_J_ISOL_VAR1			= '\uE925';
	public static final char  UNIE926_J_INIT				= '\uE926';
	public static final char  UNIE927_J_MEDI				= '\uE927';
	public static final char  UNIE928_J_FINA				= '\uE928';
	// Y
	public static final char  UNIE929_Y_ISOL				= '\uE929';
	public static final char  UNIE92A_Y_INIT				= '\uE92A';
	public static final char  UNIE92B_Y_INIT_VAR1			= '\uE92B';
	public static final char  UNIE92C_Y_MEDI				= '\uE92C';
	public static final char  UNIE92D_Y_FINA				= '\uE92D';
	// R
	public static final char  UNIE92E_R_ISOL				= '\uE92E';
	public static final char  UNIE92F_R_INIT				= '\uE92F';
	public static final char  UNIE930_R_MEDI				= '\uE930';
	public static final char  UNIE931_R_FINA				= '\uE931';
	// W
	public static final char  UNIE932_W_ISOL				= '\uE932';
	public static final char  UNIE933_W_INIT				= '\uE933';
	public static final char  UNIE934_W_INIT_VAR1			= '\uE934';
	public static final char  UNIE935_W_MEDI				= '\uE935';
	public static final char  UNIE936_W_FINA				= '\uE936';
	public static final char  UNIE937_W_FINA_VAR1			= '\uE937';
	// F
	public static final char  UNIE938_F_ISOL				= '\uE938';
	public static final char  UNIE939_F_INIT				= '\uE939';
	public static final char  UNIE93A_F_MEDI				= '\uE93A';
	public static final char  UNIE93B_F_FINA				= '\uE93B';
	public static final char  UNIE93C_FA_ISOL				= '\uE93C';
	public static final char  UNIE93D_FA_INIT				= '\uE93D';
	public static final char  UNIE93E_FA_MEDI				= '\uE93E';
	public static final char  UNIE93F_FA_FINA				= '\uE93F';
	public static final char  UNIE940_FE_ISOL				= '\uE940';
	public static final char  UNIE941_FE_INIT				= '\uE941';
	public static final char  UNIE942_FE_MEDI				= '\uE942';
	public static final char  UNIE943_FE_FINA				= '\uE943';
	public static final char  UNIE944_FI_ISOL				= '\uE944';
	public static final char  UNIE945_FI_INIT				= '\uE945';
	public static final char  UNIE946_FI_MEDI				= '\uE946';
	public static final char  UNIE947_FI_FINA				= '\uE947';
	public static final char  UNIE948_FO_ISOL				= '\uE948';
	public static final char  UNIE949_FO_INIT				= '\uE949';
	public static final char  UNIE94A_FO_MEDI				= '\uE94A';
	public static final char  UNIE94B_FO_FINA				= '\uE94B';
	public static final char  UNIE94C_FU_ISOL				= '\uE94C';
	public static final char  UNIE94D_FU_INIT				= '\uE94D';
	public static final char  UNIE94E_FU_MEDI				= '\uE94E';
	public static final char  UNIE94F_FU_FINA				= '\uE94F';
	public static final char  UNIE950_FOE_ISOL				= '\uE950';
	public static final char  UNIE951_FOE_INIT				= '\uE951';
	public static final char  UNIE952_FOE_MEDI				= '\uE952';
	public static final char  UNIE953_FOE_FINA				= '\uE953';
	public static final char  UNIE954_FOE_FINA_VAR1			= '\uE954';
	public static final char  UNIE955_FUE_ISOL				= '\uE955';
	public static final char  UNIE956_FUE_INIT				= '\uE956';
	public static final char  UNIE957_FUE_MEDI				= '\uE957';
	public static final char  UNIE958_FUE_FINA				= '\uE958';
	public static final char  UNIE959_FUE_FINA_VAR1			= '\uE959';
	public static final char  UNIE95A_FEE_ISOL				= '\uE95A';
	public static final char  UNIE95B_FEE_INIT				= '\uE95B';
	public static final char  UNIE95C_FEE_MEDI				= '\uE95C';
	public static final char  UNIE95D_FEE_FINA				= '\uE95D';
	public static final char  UNIE95E_FM_MEDI				= '\uE95E';
	public static final char  UNIE95F_FL_MEDI				= '\uE95F';
	// K
	public static final char  UNIE960_K_ISOL				= '\uE960';
	public static final char  UNIE961_K_INIT				= '\uE961';
	public static final char  UNIE962_K_MEDI				= '\uE962';
	public static final char  UNIE963_K_FINA				= '\uE963';
	public static final char  UNIE964_KA_ISOL				= '\uE964';
	public static final char  UNIE965_KA_INIT				= '\uE965';
	public static final char  UNIE966_KA_MEDI				= '\uE966';
	public static final char  UNIE967_KA_FINA				= '\uE967';
	public static final char  UNIE968_KE_ISOL				= '\uE968';
	public static final char  UNIE969_KE_INIT				= '\uE969';
	public static final char  UNIE96A_KE_MEDI				= '\uE96A';
	public static final char  UNIE96B_KE_FINA				= '\uE96B';
	public static final char  UNIE96C_KI_ISOL				= '\uE96C';
	public static final char  UNIE96D_KI_INIT				= '\uE96D';
	public static final char  UNIE96E_KI_MEDI				= '\uE96E';
	public static final char  UNIE96F_KI_FINA				= '\uE96F';
	public static final char  UNIE970_KO_ISOL				= '\uE970';
	public static final char  UNIE971_KO_INIT				= '\uE971';
	public static final char  UNIE972_KO_MEDI				= '\uE972';
	public static final char  UNIE973_KO_FINA				= '\uE973';
	public static final char  UNIE974_KU_ISOL				= '\uE974';
	public static final char  UNIE975_KU_INIT				= '\uE975';
	public static final char  UNIE976_KU_MEDI				= '\uE976';
	public static final char  UNIE977_KU_FINA				= '\uE977';
	public static final char  UNIE978_KOE_ISOL				= '\uE978';
	public static final char  UNIE979_KOE_INIT				= '\uE979';
	public static final char  UNIE97A_KOE_MEDI				= '\uE97A';
	public static final char  UNIE97B_KOE_FINA				= '\uE97B';
	public static final char  UNIE97C_KOE_FINA_VAR1			= '\uE97C';
	public static final char  UNIE97D_KUE_ISOL				= '\uE97D';
	public static final char  UNIE97E_KUE_INIT				= '\uE97E';
	public static final char  UNIE97F_KUE_MEDI				= '\uE97F';
	public static final char  UNIE980_KUE_FINA				= '\uE980';
	public static final char  UNIE981_KUE_FINA_VAR1			= '\uE981';
	public static final char  UNIE982_KEE_ISOL				= '\uE982';
	public static final char  UNIE983_KEE_INIT				= '\uE983';
	public static final char  UNIE984_KEE_MEDI				= '\uE984';
	public static final char  UNIE985_KEE_FINA				= '\uE985';
	public static final char  UNIE986_KM_MEDI				= '\uE986';
	public static final char  UNIE987_KL_MEDI				= '\uE987';
	// KH
	public static final char  UNIE988_KH_ISOL				= '\uE988';
	public static final char  UNIE989_KH_INIT				= '\uE989';
	public static final char  UNIE98A_KH_MEDI				= '\uE98A';
	public static final char  UNIE98B_KH_FINA				= '\uE98B';
	public static final char  UNIE98C_KHA_ISOL				= '\uE98C';
	public static final char  UNIE98D_KHA_INIT				= '\uE98D';
	public static final char  UNIE98E_KHA_MEDI				= '\uE98E';
	public static final char  UNIE98F_KHA_FINA				= '\uE98F';
	public static final char  UNIE990_KHE_ISOL				= '\uE990';
	public static final char  UNIE991_KHE_INIT				= '\uE991';
	public static final char  UNIE992_KHE_MEDI				= '\uE992';
	public static final char  UNIE993_KHE_FINA				= '\uE993';
	public static final char  UNIE994_KHI_ISOL				= '\uE994';
	public static final char  UNIE995_KHI_INIT				= '\uE995';
	public static final char  UNIE996_KHI_MEDI				= '\uE996';
	public static final char  UNIE997_KHI_FINA				= '\uE997';
	public static final char  UNIE998_KHO_ISOL				= '\uE998';
	public static final char  UNIE999_KHO_INIT				= '\uE999';
	public static final char  UNIE99A_KHO_MEDI				= '\uE99A';
	public static final char  UNIE99B_KHO_FINA				= '\uE99B';
	public static final char  UNIE99C_KHU_ISOL				= '\uE99C';
	public static final char  UNIE99D_KHU_INIT				= '\uE99D';
	public static final char  UNIE99E_KHU_MEDI				= '\uE99E';
	public static final char  UNIE99F_KHU_FINA				= '\uE99F';
	public static final char  UNIE9A0_KHOE_ISOL				= '\uE9A0';
	public static final char  UNIE9A1_KHOE_INIT				= '\uE9A1';
	public static final char  UNIE9A2_KHOE_MEDI				= '\uE9A2';
	public static final char  UNIE9A3_KHOE_FINA				= '\uE9A3';
	public static final char  UNIE9A4_KHOE_FINA_VAR1		= '\uE9A4';
	public static final char  UNIE9A5_KHUE_ISOL				= '\uE9A5';
	public static final char  UNIE9A6_KHUE_INIT				= '\uE9A6';
	public static final char  UNIE9A7_KHUE_MEDI				= '\uE9A7';
	public static final char  UNIE9A8_KHUE_FINA				= '\uE9A8';
	public static final char  UNIE9A9_KHUE_FINA_VAR1		= '\uE9A9';
	public static final char  UNIE9AA_KHEE_ISOL				= '\uE9AA';
	public static final char  UNIE9AB_KHEE_INIT				= '\uE9AB';
	public static final char  UNIE9AC_KHEE_MEDI				= '\uE9AC';
	public static final char  UNIE9AD_KHEE_FINA				= '\uE9AD';
	public static final char  UNIE9AE_KHM_MEDI				= '\uE9AE';
	public static final char  UNIE9AF_KHL_MEDI				= '\uE9AF';
	// C
	public static final char  UNIE9B0_C_ISOL				= '\uE9B0';
	public static final char  UNIE9B1_C_INIT				= '\uE9B1';
	public static final char  UNIE9B2_C_MEDI				= '\uE9B2';
	public static final char  UNIE9B3_C_FINA				= '\uE9B3';
	// Z
	public static final char  UNIE9B4_Z_ISOL				= '\uE9B4';
	public static final char  UNIE9B5_Z_INIT				= '\uE9B5';
	public static final char  UNIE9B6_Z_MEDI				= '\uE9B6';
	public static final char  UNIE9B7_Z_FINA				= '\uE9B7';
	// HH
	public static final char  UNIE9B8_HH_ISOL				= '\uE9B8';
	public static final char  UNIE9B9_HH_INIT				= '\uE9B9';
	public static final char  UNIE9BA_HH_MEDI				= '\uE9BA';
	public static final char  UNIE9BB_HH_FINA				= '\uE9BB';
	// RH
	public static final char  UNIE9BC_RH_ISOL				= '\uE9BC';
	public static final char  UNIE9BD_RH_INIT				= '\uE9BD';
	public static final char  UNIE9BE_RH_MEDI				= '\uE9BE';
	public static final char  UNIE9BF_RH_FINA				= '\uE9BF';
	// LH
	public static final char  UNIE9C0_LH_ISOL				= '\uE9C0';
	public static final char  UNIE9C1_LH_INIT				= '\uE9C1';
	public static final char  UNIE9C2_LH_MEDI				= '\uE9C2';
	public static final char  UNIE9C3_LH_FINA				= '\uE9C3';
	// ZH
	public static final char  UNIE9C4_ZH_ISOL				= '\uE9C4';
	public static final char  UNIE9C5_ZH_INIT				= '\uE9C5';
	public static final char  UNIE9C6_ZH_MEDI				= '\uE9C6';
	public static final char  UNIE9C7_ZH_FINA				= '\uE9C7';
	// CHI
	public static final char  UNIE9C8_CHI_ISOL				= '\uE9C8';
	public static final char  UNIE9C9_CHI_INIT				= '\uE9C9';
	public static final char  UNIE9CA_CHI_MEDI				= '\uE9CA';
	public static final char  UNIE9CB_CHI_FINA				= '\uE9CB';

	// Other Varient
	public static final char  UNIE9CC_S_FINA_VAR1			= '\uE9CC';
	public static final char  UNIE9CD_S_FINA_VAR2			= '\uE9CD';
	public static final char  UNIE9CE_B_FINA_VAR1			= '\uE9CE';
	public static final char  UNIE9CF_UE_ISOL_VAR1			= '\uE9CF';
	public static final char  UNIE9D0_BUE_ISOL_VAR2			= '\uE9D0';
	public static final char  UNIE9D1_BOE_MEDI_VAR2			= '\uE9D1';
	public static final char  UNIE9D2_BUE_MEDI_VAR2			= '\uE9D2';
	public static final char  UNIE9D3_POE_MEDI_VAR2			= '\uE9D3';
	public static final char  UNIE9D4_PUE_MEDI_VAR2			= '\uE9D4';
	public static final char  UNIE9D5_HOE_MEDI_VAR2			= '\uE9D5';
	public static final char  UNIE9D6_HUE_MEDI_VAR2			= '\uE9D6';
	public static final char  UNIE9D7_GOE_MEDI_VAR2			= '\uE9D7';
	public static final char  UNIE9D8_GUE_MEDI_VAR2			= '\uE9D8';
	public static final char  UNIE9D9_FOE_MEDI_VAR2			= '\uE9D9';
	public static final char  UNIE9DA_FUE_MEDI_VAR2			= '\uE9DA';
	public static final char  UNIE9DB_KOE_MEDI_VAR2			= '\uE9DB';
	public static final char  UNIE9DC_KUE_MEDI_VAR2			= '\uE9DC';
	public static final char  UNIE9DD_KHOE_MEDI_VAR2		= '\uE9DD';
	public static final char  UNIE9DE_KHUE_MEDI_VAR2		= '\uE9DE';
	public static final char  UNIE9E0_MM_MEDI				= '\uE9E0';
	public static final char  UNIE9E1_ML_MEDI				= '\uE9E1';
	public static final char  UNIE9E2_LL_MEDI				= '\uE9E2';
	public static final char  UNIE9E3_NGN_MEDI				= '\uE9E3';
	public static final char  UNIE9E4_NGH_FINA				= '\uE9E4';
	public static final char  UNIE9E5_NGG_FINA				= '\uE9E5';
	public static final char  UNIE9E6_BH_MEDI				= '\uE9E6';
	public static final char  UNIE9E7_BG_MEDI				= '\uE9E7';
	public static final char  UNIE9E8_PH_MEDI				= '\uE9E8';
	public static final char  UNIE9E9_PG_MEDI				= '\uE9E9';
	public static final char  UNIE9EA_FH_MEDI				= '\uE9EA';
	public static final char  UNIE9EB_FG_MEDI				= '\uE9EB';
	public static final char  UNIE9EC_KH_MEDI				= '\uE9EC';
	public static final char  UNIE9ED_KG_MEDI				= '\uE9ED';
	public static final char  UNIE9EE_KHH_MEDI				= '\uE9EE';
	public static final char  UNIE9EF_KHG_MEDI				= '\uE9EF';
	
	// Added 2012/10/29
	public static final char  UNIE9F0_BN_MEDI				= '\uE9F0';
	public static final char  UNIE9F1_PN_MEDI				= '\uE9F1';
	public static final char  UNIE9F2_GN_MEDI				= '\uE9F2';
	public static final char  UNIE9F3_FN_MEDI				= '\uE9F3';
	public static final char  UNIE9F4_KN_MEDI				= '\uE9F4';
	public static final char  UNIE9F5_KHN_MEDI				= '\uE9F5';
	public static final char  UNIE9F6_YIN_ISOL				= '\uE9F6';	// not used
	public static final char  UNIE9F7_ON_ISOL				= '\uE9F7';	// not used
	public static final char  UNIE9F8_UN_ISOL				= '\uE9F8';	// not used
	public static final char  UNIE9F9_OD_ISOL				= '\uE9F9';	// not used
	public static final char  UNIE9FA_UN_ISOL				= '\uE9FA';	// not used
	public static final char  UNIE9FB_YI_ISOL				= '\uE9FB';	// not used
	public static final char  UNIE9FC_YIAN_ISOL				= '\uE9FC';	// not used
	public static final char  UNIE9FD_YIEN_ISOL				= '\uE9FD';	// not used
	public static final char  UNIE9FE_YIAR_ISOL				= '\uE9FE';	// not used
	public static final char  UNIE9FF_YIER_ISOL				= '\uE9FF';	// not used
	
	public static final char  UNIEA00_H_ISOL_VAR2			= '\uEA00';
	public static final char  UNIEA01_H_INIT_VAR3			= '\uEA01';
	public static final char  UNIEA02_H_ISOL_VAR1			= '\uEA02';
	public static final char  UNIEA03_H_INIT_VAR2			= '\uEA03';
	public static final char  UNIEA04_H_MEDI_VAR2			= '\uEA04';
	public static final char  UNIEA05_HE_ISOL_VAR1			= '\uEA05';
	public static final char  UNIEA06_HE_INIT_VAR1			= '\uEA06';
	public static final char  UNIEA07_HE_MEDI_VAR1			= '\uEA07';
	public static final char  UNIEA08_HE_FINA_VAR1			= '\uEA08';
	public static final char  UNIEA09_HI_ISOL_VAR1			= '\uEA09';
	public static final char  UNIEA0A_HI_INIT_VAR1			= '\uEA0A';
	public static final char  UNIEA0B_HI_MEDI_VAR1			= '\uEA0B';
	public static final char  UNIEA0C_HI_FINA_VAR1			= '\uEA0C';
	public static final char  UNIEA0D_HOE_ISOL_VAR1			= '\uEA0D';
	public static final char  UNIEA0E_HOE_INIT_VAR1			= '\uEA0E';
	public static final char  UNIEA0F_HOE_MEDI_VAR2			= '\uEA0F';
	public static final char  UNIEA10_HOE_FINA_VAR2			= '\uEA10';
	public static final char  UNIEA11_HOE_FINA_VAR3			= '\uEA11';
	public static final char  UNIEA12_HUE_ISOL_VAR1			= '\uEA12';
	public static final char  UNIEA13_HUE_INIT_VAR1			= '\uEA13';
	public static final char  UNIEA14_HUE_MEDI_VAR2			= '\uEA14';
	public static final char  UNIEA15_HUE_FINA_VAR2			= '\uEA15';
	public static final char  UNIEA16_HUE_FINA_VAR3			= '\uEA16';
	public static final char  UNIEA17_HEE_ISOL_VAR1			= '\uEA17';
	public static final char  UNIEA18_HEE_INIT_VAR1			= '\uEA18';
	public static final char  UNIEA19_HEE_MEDI_VAR1			= '\uEA19';
	public static final char  UNIEA1A_HEE_FINA_VAR1			= '\uEA1A';
	public static final char  UNIEA1B_G_ISOL_VAR2			= '\uEA1B';
	public static final char  UNIEA1C_G_ISOL_VAR1			= '\uEA1C';
	public static final char  UNIEA1D_G_INIT_VAR3			= '\uEA1D';
	public static final char  UNIEA1E_G_INIT_VAR2			= '\uEA1E';
	public static final char  UNIEA1F_G_MEDI_VAR3			= '\uEA1F';
	
	public static final char  UNIEA20_OE_MEDI_VAR1			= '\uEA20';
	public static final char  UNIEA21_A_INIT_VAR1			= '\uEA21';
	public static final char  UNIEA22_Y_MEDI_VAR1			= '\uEA22';
	public static final char  UNIEA23_N_FINA_VAR2			= '\uEA23';
	public static final char  UNIEA24_BIRGA_VAR1			= '\uEA24';
	public static final char  UNIEA25_BIRGA_VAR2			= '\uEA25';
	public static final char  UNIEA26_BIRGA_VAR3			= '\uEA26';
	public static final char  UNIEA27_BIRGA_VAR4			= '\uEA27';
	
	public static final char  UNIEA31						= '\uEA31';
	public static final char  UNIEA35						= '\uEA35';
	public static final char  UNIEA36						= '\uEA36';
	public static final char  UNIEA3D						= '\uEA3D';
	public static final char  UNIEA3E						= '\uEA3E';
	public static final char  UNIEA3F						= '\uEA3F';
	public static final char  UNIEA40						= '\uEA40';
	public static final char  UNIEA41						= '\uEA41';
	public static final char  UNIEA42						= '\uEA42';
	public static final char  UNIEA43						= '\uEA43';
	public static final char  UNIEA44						= '\uEA44';
	public static final char  UNIEA47						= '\uEA47';
	public static final char  UNIEA48						= '\uEA48';
	
	public static final char  UNIFE10						= '\uFE10';
	public static final char  UNIFE11						= '\uFE11';
	public static final char  UNIFE12						= '\uFE12';
	public static final char  UNIFE14						= '\uFE14';
	public static final char  UNIFE15						= '\uFE15';
	public static final char  UNIFE16						= '\uFE16';
	public static final char  UNIFE19						= '\uFE19';
	public static final char  UNIFE35						= '\uFE35';
	public static final char  UNIFE36						= '\uFE36';
	public static final char  UNIFE3D						= '\uFE3D';
	public static final char  UNIFE3E						= '\uFE3E';
	public static final char  UNIFE3F						= '\uFE3F';
	public static final char  UNIFE40						= '\uFE40';
	public static final char  UNIFE41						= '\uFE41';
	public static final char  UNIFE42						= '\uFE42';
	public static final char  UNIFE43						= '\uFE43';
	public static final char  UNIFE44						= '\uFE44';	
	public static final char  UNIFE47						= '\uFE47';
	public static final char  UNIFE48						= '\uFE48';
	
}
